### ISSUE TITLE
Failed assertion on mouse page

### ISSUE THREAD

**Issue by Jupi007** [Feichtmeier/settings#1]
![Capture d’écran du 2021-07-05 22-43-43](https://user-images.githubusercontent.com/36476595/124516698-8e056e00-dde2-11eb-9271-6469aa644d80.png)

```console
════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/material/slider.dart': Failed assertion: line 165 pos 15: 'value >= min && value <= max': is not true.
The relevant error-causing widget was
SliderRow                         lib/…/mouse_and_touchpad/mouse_section.dart:31
════════════════════════════════════════════════════════════════════════════════

```

**Comment by Feichtmeier** [comment]
Strange :thinking: 
Maybe the mouse speed or something
![grafik](https://user-images.githubusercontent.com/15329494/124517108-6ebb1080-dde3-11eb-8bfb-36b52f99c53f.png)

Thanks @Jupi007 !

**Comment by Jupi007** [comment]
Your welcome !
I'm happy to help you a bit on this :)

**Comment by Feichtmeier** [comment]
I guess the range of the slider needs to be specified in case the value is negative, which is possible for mouse speed :) sure, feel free to grab :+1:

**Comment by Jupi007** [comment]
> I guess the range of the slider needs to be specified in case the value is negative, which is possible for mouse speed :) sure, feel free to grab +1

I'll take a look tomorrow :)

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/Feichtmeier/settings/commit/e512da0e670a0a421370b18516827b4fee2d0bef (sorry for the grab, this issue was too big ^^ and thanks for noting)
