### ISSUE TITLE
Errors on fast Info page changes

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#108]
![Peek 2021-09-30 09-38](https://user-images.githubusercontent.com/15329494/135408846-4ad5a790-28a2-4076-b13d-797cf970c1b7.gif)

**Comment by Feichtmeier** [comment]
Idea: could we eventually load all the DI stuff inside main? For all pages? Ofc this would increase the heap for startup but maybe it helps on those fast page swaps

**Comment by jpnurmi** [comment]
Currently, services are (lazily) provided from main to avoid. It's also a possibility to make some of them pre-load and cache data.

That exception on fast page switch looks like a bug that needs to be addressed somewhere in the change notifiers or services. :)

**Comment by jpnurmi** [comment]
A wild guess without any testing:
```diff
diff --git a/lib/services/hostname_service.dart b/lib/services/hostname_service.dart
index 1295499..8f7ecc8 100644
--- a/lib/services/hostname_service.dart
+++ b/lib/services/hostname_service.dart
@@ -23,7 +23,7 @@ class HostnameService {
 
   Future<void> init() async {
     await _initProperties();
-    _propertyListener = _object.propertiesChanged.listen(_updateProperties);
+    _propertyListener ??= _object.propertiesChanged.listen(_updateProperties);
   }
 
   Future<void> dispose() async {
```

**Comment by jpnurmi** [comment]
Oh, right. That explains. :)

GSettings objects are managed by the new SettingsService. When a model asks for a settings object from the service, the service either creates one if necessary, or returns an existing one from the internal cache if it already exists. The SettingsService is also in charge of disposing the settings objects so it doesn't need to be done all over the place. This means that pages must no longer dispose the settings objects because they might be in the cache. I hope that makes sense. :)

**Comment by Feichtmeier** [comment]
Sadly this does not purge the error - the error message is:

```bash
Restarted application in 371ms.
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:635:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#3      DBusSignalStream.listen
#4      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#5      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#6      _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#7      UDisksClient.connect
#8      InfoModel.init
<asynchronous suspension>
```
![Peek 2021-10-01 23-31](https://user-images.githubusercontent.com/15329494/135688460-af01e111-1f10-4271-8737-0d3fed46d737.gif)
