### ISSUE TITLE
Make it possible to have individuals FABs on pages

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#112]
With the current architecture it feelds kind of hard to insert individual FABs for pages if wanted.

I found it could be made possible via PageItem but then I have hard times to access the model from there - any idea @jpnurmi @mivoligo or anyone else?

![grafik](https://user-images.githubusercontent.com/15329494/135710349-fb51c4cc-ce0a-42e5-ab85-7e050a08795a.png)

**Comment by jpnurmi** [comment]
I'm afraid the idea of having a global list of PageItems is not going to work because there's no BuildContext available, which means that localizations wouldn't be available either. When you place widgets in the widget tree where a context is available, you will be able to access any provided service and model too.

**Comment by Feichtmeier** [comment]
> I'm afraid the idea of having a global list of PageItems is not going to work because there's no BuildContext available, which means that any services, models, or localizations wouldn't be available either. When you place widgets in the widget tree where a context is available, you will be able to access any provided objects too.

hmmm this is bad. Because the pages are wrapped inside singlechildscrollviews already, if you put a FAB via stack onto a page it scrolls with the page :( 
I would prefer if the pageitem has a nullable FAB as an attribute and each pageitem could define it's own FAB. The FAB action would then be taken from the page or the model - really no way we could do this? I would prefer a FAB in some cases where you add stuff like the wallpaper page or printers or users page

**Comment by jpnurmi** [comment]
I think I phrased it wrong and probably misunderstood the problem too. ​I'm not saying you cannot have FAB's, scrollable pages, or anything else built out of widgets. 🙂

I understood you wanted have or create FAB's in PageItems, but the context would be wrong because they'd be called from a different context than where the page is.

What I meant to say is that it's better to keep widgets in their natural place in the widget tree, where they have access to anything they need.

**Comment by Feichtmeier** [comment]
What I would like is this:

```dart
class PageItem {
  const PageItem(
      {required this.title,
      required this.builder,
      required this.iconData,
      this.fab});
  final String title;
  final WidgetBuilder builder;
  final IconData iconData;
  final FloatingActionButton? fab;
}
```

then pages could have a FAB or not

for example the wallpaper page would then be inserted like

```dart
PageItem(
    title: 'Wallpaper',
    iconData: YaruIcons.desktop_wallpaper,
    builder: WallpaperPage.create,
    fab: WallpaperFloatingActionButton()
  ),
```
and the WallpaperFloatingActionButton would just call a model action, but the problem is that I can not access the model from the FAB because the model is already attached to the WallpaperPage

**Comment by jpnurmi** [comment]
Oops, mobile touch fail :D

**Comment by Feichtmeier** [comment]
and the landscape layout could then use

```dart
class _LandscapeLayoutState extends State<LandscapeLayout> {
...

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: widget.pages[_selectedIndex].fab,
...
```

**Comment by jpnurmi** [comment]
Imagine that each setting page would be a separate package aka "module" and they wouldn't strictly assume the structure of the host app.

When it comes to communication, passing simple callbacks is a common way to communicate in a way the it allows both ends to process events in their own context.

**Comment by jpnurmi** [comment]
> for example the wallpaper page would then be inserted like
> 
> ```dart
> PageItem(
>     // ...
>     fab: WallpaperFloatingActionButton() // <== :(
>   ),
> ```

Please don't create widgets out of context. Creating parentless widget babies is irresponsible! :point_up:

**Comment by Feichtmeier** [comment]
Even though I understand more stuff here now, since you explained it to me in the context (pun intended) of titles, FABs are not really needed anymore from a design perspective! Closing
