### ISSUE TITLE
Kernel error if a power profile is not availible 

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#124]
![grafik](https://user-images.githubusercontent.com/15329494/135759425-f59680e2-cdd7-4264-b84f-41493eee36aa.png)

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: org.freedesktop.DBus.Error.Failed: Profile 'performance' is inhibited
#0      DBusClient._callMethod
<asynchronous suspension>
#1      DBusClient.callMethod
<asynchronous suspension>
#2      DBusRemoteObject.setProperty
<asynchronous suspension>
```

**Comment by Feichtmeier** [comment]
Kinda weird. The label says that the reason is that a laptop was detected. But I'm pretty sure this worked when the battery was full. So either they changed this in 21.10 or the label in GCC is just plain wrong

**Comment by Feichtmeier** [comment]
Yep, everything fine for laptops, just the label is wrong :)  

![grafik](https://user-images.githubusercontent.com/15329494/135760279-9ba6687c-3196-4766-9513-5d010176287b.png)

**Comment by jpnurmi** [comment]
The high-performance profile is not available when the battery is low?

**Comment by Feichtmeier** [comment]
> 
> 
> The high-performance profile is not available when the battery is low?

yes
when the battery is low. otherwise it's availible

**Comment by Feichtmeier** [comment]
Oh, actually I've fixed this :D
