### ISSUE TITLE
Appearance page: too much space used

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#131]
Imo the current appearance page uses too much space for the first section.
![grafik](https://user-images.githubusercontent.com/15329494/135886192-5c8ffe03-85e0-4a5c-bbc1-b321473ee6de.png)

It is actually the dark mode section. How about this simple solution:

![grafik](https://user-images.githubusercontent.com/15329494/135885598-29bd409b-3b45-422d-8a6c-9a0b8b65bce6.png)

![onoff](https://user-images.githubusercontent.com/15329494/135885939-b8a360a1-bbc4-4a8c-a4e0-14a4081fc56f.gif)

**Comment by madsrh** [comment]
I do love any kind of "bling", but this card solution isn't working, so I'm +1 for removing it.
Your suggestion is super simple and 100% works.

Maybe it's just the implementation that isn't perfect 🤷‍♂️ Perhaps something simpler?

![image](https://user-images.githubusercontent.com/3986894/135892417-a7ef3bc2-7e75-4d2d-a87e-66f85a211449.png)

It just add an icon

![image](https://user-images.githubusercontent.com/3986894/135892533-51a3f1e6-89f1-4d02-876c-050c97242b48.png)

**Comment by Jupi007** [comment]
@Feichtmeier Good idea :)

**Comment by Feichtmeier** [comment]
The trailing icon is a good idea, but we need a new widget for this which is no problem. I try later

**Comment by Feichtmeier** [comment]
haha so much refactoring for the row but it is a good idea and we could use this pattern with the trailing icon elsewhere. 

![grafik](https://user-images.githubusercontent.com/15329494/135931500-a09a31af-55ed-46a2-98c9-5f496b75854d.png)

and this screenshot almost burned out my eye...
![grafik](https://user-images.githubusercontent.com/15329494/135931538-e9a7cdd8-6d0f-414a-9ddf-62a8e7f0ec2c.png)

**Comment by Feichtmeier** [comment]
@Jupi007 
![Peek 2021-10-05 09-52](https://user-images.githubusercontent.com/15329494/135982625-c190cd54-797e-4003-9dd6-bbb63ad2ec2d.gif)
is this okay or you think we need explicit yaru icons for this? took the weather icons ^^

**Comment by Jupi007** [comment]
> @Jupi007 ![Peek 2021-10-05 09-52](https://user-images.githubusercontent.com/15329494/135982625-c190cd54-797e-4003-9dd6-bbb63ad2ec2d.gif) is this okay or you think we need explicit yaru icons for this? took the weather icons ^^

Imo these ones looks very good :)
