### ISSUE TITLE
Add a background color

### ISSUE THREAD

**Issue by madsrh** [Feichtmeier/settings#14]
I don't know if it's just because I see the GTK settings app all the time, but I really miss the white background for the content. The current gray wall 😄 gives it a bit of an old-school vibe.
It helps separate elements and I would also love to see this for the sidebar. 

Mockup:
![image](https://user-images.githubusercontent.com/3986894/125870597-f634531e-e5b1-49f9-bb16-7365405be620.png)

Current:
![image](https://user-images.githubusercontent.com/3986894/125870917-81e84ed5-8aa7-470c-a7f3-d0f8510fe9d5.png)

**Comment by Feichtmeier** [comment]
I prefer it without many background colour changes but I will test this

**Comment by madsrh** [comment]
Alright 👍 The background looks like #f7f7f7. Perhaps just changing it to #fafafa 🤷‍♂️ 
What's the background color for the Canonical installer?

**Comment by Feichtmeier** [comment]
Hm thinking about this for a while but I really like the clean look of one bg color plus the subtle borders
![grafik](https://user-images.githubusercontent.com/15329494/134489467-99689cc2-af74-4ba6-a4c4-d1f51e9a93ad.png)

I hope you don't mind if I close this issue? :angel:

**Comment by madsrh** [comment]
OFC I don't mind 😁 But would you consider making the background slightly brighter?

**Comment by Feichtmeier** [comment]
I did not change any colors inside the app but we can talk about this in yaru.dart :D :D :D opening an issue to discuss there :dancers:
