### ISSUE TITLE
Align search icon with list tile icons

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#145]
Just curious, is it a deliberate choice that you didn't align it?

![image](https://user-images.githubusercontent.com/3986894/136581360-93981189-afb3-4d40-81f6-3e8c0bcdc7ed.png)

_Originally posted by @madsrh in https://github.com/Feichtmeier/settings/issues/143#issuecomment-938724399_

**Comment by madsrh** [comment]
> I am not sure if it should be aligned vertically though - for my eyes it does not need to be on this "axis"

🤷‍♂️ And yet you merged it anyway? I agree, it doesn't have to be aligned, but when it is, the layout is more "calm" (not sure if that is the correct translation).
