### ISSUE TITLE
Wi-Fi page thoughts

### ISSUE THREAD

**Issue by madsrh** [Feichtmeier/settings#166]
As always, if you disagree with any of these thoughts, feel free to close this issue 😄 

- Typo: The label needs to be renamed to Wi-Fi (not wifi)

- Maybe a stupid question, but what is this **wlp0s20f3**? I genuinely don't know 🙈 I was expecting something like "**Available connections:**"

![image](https://user-images.githubusercontent.com/3986894/141598283-4257bb26-9e76-43c9-b915-00ede89fc769.png)

- Below the label is the place for the gray help texts. Values like CONNECTED should "float right" and be placed next to the toggle, like we do on [the Accessibility page ](https://user-images.githubusercontent.com/3986894/141598632-033b927e-e972-4e68-acbc-8df10cfc3551.png
)

![image](https://user-images.githubusercontent.com/3986894/141598469-d1f01c59-e48c-4d68-b371-82176f146512.png)

- In the light theme there's no gray background to indicate that Wi-Fi is selected
![image](https://user-images.githubusercontent.com/3986894/141598776-1b81263e-b0cc-4a1f-ab51-f4b376e37c17.png)

**Comment by madsrh** [comment]
I had a look at the Canonical mockups and did a "consolidated version" of their connections page ;) 

![image](https://user-images.githubusercontent.com/3986894/141599292-863580a0-6eb0-42e5-a449-f3b1e27c0ad8.png)

**Comment by Feichtmeier** [comment]
Thanks @madsrh !
Will fix this
Also I didn't find the icon for cellular network but I'm sure it's there

**Comment by Feichtmeier** [comment]
@madsrh 

![grafik](https://user-images.githubusercontent.com/15329494/141644406-13d7acec-23df-4601-bd25-24eaf1f2327e.png)

![grafik](https://user-images.githubusercontent.com/15329494/141644437-587ac319-0bb9-4353-9002-ecb9c4c31d0f.png)

**Comment by madsrh** [comment]
🎉 @Feichtmeier 

Only missing the Wi-Fi typo 📶

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/141644958-8841c042-9d7a-4e84-99e1-81508c9554d9.png)

And a missing cellular network icon :angel: 
@Jupi007 Could you add it if you have time?

**Comment by Jupi007** [comment]
> And a missing cellular network icon angel
> @Jupi007 Could you add it if you have time?

Ofc :)
