### ISSUE TITLE
Upgrade gsettings.dart to 0.2+

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#183]
The package has been completely reworked. Updating to 0.2+ will most likely fix https://github.com/Feichtmeier/settings/issues/182
as suggested here by JP: https://github.com/canonical/gsettings.dart/issues/22#issuecomment-991661694

**Comment by jpnurmi** [comment]
I can help with this. 🙂 There are some fixes needed in gsettings.dart 0.2 too.
