### ISSUE TITLE
Missing page: WIFI

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#20]
Must have features:

- visualize all visible wifi networks and mark the one one is connected to
- let the user connect to a wifi network in the list
- let the user disconnect from the currently connected wifi network

Optional:
- let the user disable wifi, bluetooth and celuar networks via an "Airplane mode" button (IMO since this feature belongs to different pages it should not be put into one page but rather in the AppBar, but we need to experiment on this one)

Relevant implementations:

- gnome control center
![grafik](https://user-images.githubusercontent.com/15329494/126029984-0b391ba1-ac2c-46fb-a3a1-286a97c81695.png)

- unity8 settings
![grafik](https://user-images.githubusercontent.com/15329494/126030146-0343d3f9-b952-4095-9962-debcb83f02bb.png)

**Comment by HosamHasanRamadan** [comment]
I will work on this page as soon as possible

**Comment by Feichtmeier** [comment]
Thanks to @HosamHasanRamadan we are a good step forward here.

Features missing:

- select encryption method
- connect to hidden wifi networks
- a connection settings dialog inlcuding a forget connection button
