### ISSUE TITLE
Power page crash due to Power.Keyboard property

### ISSUE THREAD

**Issue by Jupi007** [Feichtmeier/settings#205]
**Note:** I'm using a desktop computer without any control of brightness.

It looks like the app crash because I don't have the `org.gnome.SettingsDaemon.Power.Keyboard` schema installed.

```
DBusFailedException (org.freedesktop.DBus.Error.Failed: Failed to get property Brightness on interface org.gnome.SettingsDaemon.Power.Keyboard)
```

_In `power_settings_service.dart` line 80._

@Feichtmeier I hope this one is not duplicated 😅

**Comment by mivoligo** [comment]
Hey @Jupi007 I have the same issue. Although for me the doesn't crash, just the error shows up in the console.
I have an idea how to fix it but can you check one thing for me, please?
Can you try moving the screen brightness slider and see if it changes position for you? For me it does not but for @Feichtmeier (who has working keyboard brightness) it does work.

I believe those issues are related :)

**Comment by Jupi007** [comment]
@mivoligo Just retried: the slider doesn't move at all. The app doesn't crash, and there's indeed an error in debug console:
```
Unhandled Exception: org.freedesktop.DBus.Error.Failed: Failed to get property Brightness on interface org.gnome.SettingsDaemon.Power.Keyboard
```

**Comment by mivoligo** [comment]
@Jupi007 Thanks! I'll create a PR later on.

**Comment by Jupi007** [comment]
Nice :)
Thank you!

**Comment by mivoligo** [comment]
Checkout the PR when you find some time :)
