### ISSUE TITLE
PowerPage: round the battery bar

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#207]
![grafik](https://user-images.githubusercontent.com/15329494/146750760-50d7fa30-4c61-4ff1-a275-e614988000db.png)

**Comment by Jupi007** [comment]
We can wrap the progress inside a `ClipRRect`:

```dart
ClipRRect(
  borderRadius: BorderRadius.all(Radius.circular(3)),
  child: LinearProgressIndicator(...),
)
```

Maybe also create a new yaru widget `YaruLinearProgressIndicator`?

**Comment by Feichtmeier** [comment]
Good idea because it is not changeable within the material theme!
