### ISSUE TITLE
SimpleDialog widget miss a close button

### ISSUE THREAD

**Issue by Jupi007** [Feichtmeier/settings#209]
I know I can close the dialog by click outside, but I always feel uncomfortable when a dialog don't have a close button (and I think some other people can also be like me).

I propose to create a `YaruSimpleDialog` widget like this (this will also allow to centralise padding infos):

![Capture d’écran du 2021-12-20 00-30-50](https://user-images.githubusercontent.com/36476595/146761085-8c37b14e-9fda-40f3-a30d-020144b4f4f8.png)

**Comment by Feichtmeier** [comment]
Nice idea!

**Comment by Feichtmeier** [comment]
Could you do this in 
yaru_widgets.dart ?

**Comment by Jupi007** [comment]
Yes, ofc :)
