### ISSUE TITLE
Infographics when dock position is other than default

### ISSUE THREAD

**Issue by mivoligo** [Feichtmeier/settings#229]
I've noticed the new lovely graphics on Appearance and Multi-tasking pages :heart_eyes: 
Personally I have my dock at the bottom of the screen and the graphics have dock on the left.
What do you think of creating more of the graphics for different dock positions and displaying them according to the current dock position selected by a user?

**Comment by Feichtmeier** [comment]
Would be very nice

@Muqtxdir could you do this when you have time?

**Comment by Muqtxdir** [comment]
> What do you think of creating more of the graphics for different dock positions and displaying them according to the current dock position selected by a user?

I like this idea, thanks for this suggestion.

>Would be very nice
@Muqtxdir could you do this when you have time?

sure, I'll create them for other remaining positions.

**Comment by Feichtmeier** [comment]
Fixed :) thanks everyone
