### ISSUE TITLE
Missing page: Info

### ISSUE THREAD

**Issue by madsrh** [Feichtmeier/settings#24]
Must have features:

- System specs
- OS information

Optional:

- Ability to edit the device name
- OS logo
- Shortcut for software updates

Mockup:
![image](https://user-images.githubusercontent.com/3986894/126236386-fdc5c32f-be97-4092-a915-28de6392c296.png)

**EDIT:** Not sure about the "System updates" button. Perhaps it's unnecessary to be able up launch the updater from here. 
Would it make more sense to move "Device name" to the bottom of the list? Also if it's possible to rename the device from here (_it can also be done from the Sharing screen_), there should be a button or something that indicates that the device name is clickable.

**Comment by Feichtmeier** [comment]
I would like to not include all those borders between the rows if you are okay with this? :) @madsrh

**Comment by Jupi007** [comment]
@Feichtmeier My PR on `linux_system_info` is merged: https://github.com/LolzDEV/linux_system_info/pull/1

Just wait for a new release!
