### ISSUE TITLE
Review architecture

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#27]
After playing around with the bluetooth page, whichs UI is straight forward, I quickly came near the limits of setState().
After seeing the power of separating the view from the viewmodel plus a chanfelistener in https://github.com/canonical/ubuntu-desktop-installer/issues/147 I think we should also do this for this app.
It is an additional effort but I think the more complicated pages will profit from this. 
Eventually we can keep the gsettings pages like they currently are.

**Comment by mivoligo** [comment]
I'm all for it after starting messing around with more complicated parts of Accessibility page. I got too much spaghetti code real quick. I think I'll try to implement that page using Provider and ChangeNotifier as you referenced above.

**Comment by Feichtmeier** [comment]
Good idea :)
Simple page stuff with setState really only works for single toggles/sliders.
Anything more complicated needs the MVVM pattern from @jp-nurmi

**Comment by Feichtmeier** [comment]
I think we've successfully converted all pages to the MVVM pattern and wow so much better - thank you very much @jpnurmi for putting us on this path, everything is so much more easy and structured now :tada: 

Thus closing !
