### ISSUE TITLE
Missing feature: search settings page

### ISSUE THREAD

**Issue by madsrh** [Feichtmeier/settings#28]
I know it's just a WIP placeholder, but the large **Settings** label should be replaced with a textfield / searchfield.

![image](https://user-images.githubusercontent.com/3986894/126230724-fb63e790-8f69-4434-bc6f-96305c15394d.png)

When the field isn't active, a grayed out **Search** label is visible. 

![image](https://user-images.githubusercontent.com/3986894/126233209-f29363cb-778f-4790-ad3e-b085b6419cfb.png)

As the user enters a query, matching results are displayed in the sidebar below (or as a dropdown)

![image](https://user-images.githubusercontent.com/3986894/126232726-d959cba4-1a22-44d2-adef-1d6bd0e5245f.png)

**Comment by Feichtmeier** [comment]
Thanks for the issue - yes this is currently only lipstick.
However I am not entirely sure about how search should work. I somehow do not like how the left row suddenly becomes an area of other elements.
I rather thought about some kind of search popup / dialog
but we can try different things :)

**Comment by madsrh** [comment]
> ... I somehow do not like how the left row suddenly becomes an area of other elements...

+1 that is a bit weird. It's just the way the sidebar works in GCC, but a popup / dialog might be better. That was also what I meant by _"or as a dropdown"_ 😅 

![image](https://user-images.githubusercontent.com/3986894/126403904-1a070ac9-1340-423f-9e15-2c17b1eaa9ae.png)

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/133108132-bfaea772-4899-4bfe-bcc3-d193f000c0be.png)

**Comment by Feichtmeier** [comment]
@madsrh WDYT about rather a search dialog opening up?

![FLAMESHOT_2021-09-15_15-42_1](https://user-images.githubusercontent.com/15329494/133444492-0d4125cf-431e-4bb0-bf73-6ac511da70fa.png)
![FLAMESHOT_2021-09-15_15-42](https://user-images.githubusercontent.com/15329494/133444497-fe6b1527-b14e-45ce-aebd-e0a4ac4e65c8.png)

**Comment by madsrh** [comment]
> WDYT about rather a search dialog opening up?

@Feichtmeier It could work but doesn't it feel a bit disconnected compared to the search field like you posted here:

![image](https://user-images.githubusercontent.com/3986894/133459117-9fa80cbb-70da-4b58-a88f-147c3061a47f.png)

**Comment by madsrh** [comment]
Why is this issue reopened @Feichtmeier ?

You properly can't tell from my comment above, but I am a fan of floating action buttons - just not on the desktop. IMHO there's two issues here:
- The green circle is very attention grabbing (is green the correct color here?)
- The placement of the icon (I know it's aligned with the sidebar border). I've tried moving it to the bottom, but this looks odd too 🤷‍♂️ 

Looking through the material documentation, all images I can find have a tradition searchbar accompaniment by a FAB icon. 

As always, I'm just sharing my opinion, so feel free to dismiss this comment 😅  

![fab](https://user-images.githubusercontent.com/3986894/134037465-bfa7c4cf-6e8f-4de0-8334-3f42abe5d1d2.gif)

Just brainstorming here 😄 
![image](https://user-images.githubusercontent.com/3986894/134040000-99d2ecf4-1649-4434-bb6e-e2e43eb25c24.png)

**Comment by Feichtmeier** [comment]
Totally agree @madsrh 

I've reopened because I wanted a better solution plus I'm redoing navigation and this thing is starting to become crap code (by me). I will try what you suggested

**Comment by madsrh** [comment]
I do prefer this approach. Feels/looks much more coherent.

Question: when you launch the app, is the search field in focus so you can start typing right away? (Like in GSC)

**Comment by Feichtmeier** [comment]
Could be possible to do yes. Currently you first need to click the search button
