### ISSUE TITLE
left pane width - 280 or less?

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#289]
Sometimes I feel that 280 is too large for the left pane

| 280 | 260 |
|-|-|
|![Bildschirmfoto von 2022-02-22 12-33-18](https://user-images.githubusercontent.com/15329494/155124282-cd599982-111a-4d10-afdf-6694c4021088.png) | ![Bildschirmfoto von 2022-02-22 12-33-02](https://user-images.githubusercontent.com/15329494/155124287-8de31e4b-767c-47fa-8b5b-f4796a5660cd.png) |

Disadvante is that some page item labels are 2 line now :S 
Opinions @Jupi007  @madsrh ?

**Comment by Jupi007** [comment]
Honestly, I think the line break is worst to see than the larger pane width.

**Comment by madsrh** [comment]
Definitely 280px

You can't guarantee that this will prevent some labels having 2 lines without considering all the translations 🌐

If anything, you should consider making the sidebar font a tiny bit smaller or play with the letter spacing. I know these are standard values, so you properly won't mess with them, so better go with 280 😎 

How does it stack up when compared to the settings in your browser? I know that isn't GTK, but neither is this 😄

**Comment by Feichtmeier** [comment]
Well, we could use the elipses dots for overfloating text in the list tile?
![image](https://user-images.githubusercontent.com/15329494/155169780-faafa8c0-dfe9-4fb1-b7e4-08fd9ce3aa60.png)

**Comment by madsrh** [comment]
> Do you mean chrome settings?

Yes, that looks to mostly resemble the 280 width 🧐 

> we could use the elipses dots for overfloating text in the list tile?

I would still prefer a wider sidebar, but perhaps both (wide sidebar and dots)? The dots wouldn't be used in english, but are there in case some language would have a long string.

**Comment by Feichtmeier** [comment]
Okay, let's do dots plus 280 sidebar then :) closing!
