### ISSUE TITLE
InfoPage: skip gpu info if not available

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#297]
![image](https://user-images.githubusercontent.com/15329494/157198773-36184d67-21d8-4d07-8f53-60eeb7de2ddd.png)

This error appears when loading this page in a gnome boxes VM. 
@Jupi007 could you take a look?

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:360:5)
#1      InfoModel.init.<anonymous closure>
#2      _rootRunUnary (dart:async/zone.dart:1434:47)
<asynchronous suspension>
#3      InfoModel.init
<asynchronous suspension>
```

**Comment by Jupi007** [comment]
I'll take a look :+1:

**Comment by Feichtmeier** [comment]
Thanks :)
Actually there is info, GCC says:

Graphics: llvmpipe (LLVM 12.0.1, 256 bits)

**Comment by Jupi007** [comment]
This is related to the used library, so.
I remember @jpnurmi worked on it.

But it still require to fix when no value is sent.
