### ISSUE TITLE
Add descriptions

### ISSUE THREAD

**Issue by madsrh** [Feichtmeier/settings#31]
Some labels aren't very descriptive. For instance the average user doesn't know the difference between _event sounds_ and _input feedback sounds_. There's a subtext (is that a word?) in Dconf-editor, which (sometimes) adds a bit more information.

It could say something like:

**Event-sounds**
_Notify the user of a system action, notification or event_
**Input-feedback-sounds**
_Feedback for user input events, such as mouse clicks, or key presses._

https://specifications.freedesktop.org/sound-naming-spec/sound-naming-spec-latest.html

![image](https://user-images.githubusercontent.com/3986894/127738628-f483c4b6-8cf6-4589-89fb-b32e75afbce7.png)

**EDIT:** Or the user could just have a slider where you choose the level of sounds. Like: No sound, some sounds, all sounds 🤷‍♂️ Just a thought

**Comment by Feichtmeier** [comment]
@mivoligo introduced descriptions for setting rows
![Bildschirmfoto von 2021-09-15 12-29-06](https://user-images.githubusercontent.com/15329494/133417547-079cf9c8-9b12-4c06-84ca-3d852bddc054.png)

If it is needed for individual rows we can open individual bugs for it - thanks everyone :+1:
