### ISSUE TITLE
Changing some settings do not work well

### ISSUE THREAD

**Issue by mivoligo** [Feichtmeier/settings#310]
I've noticed that changing some settings do not really work.
For example: In Power page I change "Blank screen" to any value and it always results in 300 seconds. That value is the default value for that settings according to Dconf Editor.
![power](https://user-images.githubusercontent.com/1629120/159007941-45f7a057-4e21-4d15-9a6c-2edf3c908330.gif)

Similar issue is with:
1. Privacy > House Keeping > Recycle bin > Period for automatic deletion
2. Privacy > House Keeping > Screen Lock > both delay settings

**Comment by mivoligo** [comment]
FWIW I've noticed all of those values are of type `Unsigned 32-bit integer` according to dconf. Meanwhile the setting which works properly: "Period of file history" (/org/gnome/desktop/privacy/recent-files-max-age) is of type `Signed 32-bit integer`.

**Comment by mivoligo** [comment]
So I think the issue might be here: https://github.com/Feichtmeier/settings/blob/32b7b128f0b38a5c3d504ee9112e8f360614808e/lib/services/settings_service.dart#L80

Here's the code in dbus for unsigned integer: https://github.com/canonical/dbus.dart/blob/e003b66747ba0dea6ed4084a74331bd35d0a8af5/lib/src/dbus_value.dart#L208

**Comment by Feichtmeier** [comment]
Nice finding. This could be indeed an issue. So should we add one case for each type of int in the settingsservice?

**Comment by mivoligo** [comment]
I believe so but not sure how to handle that properly. Maybe @jpnurmi could help here.

**Comment by jpnurmi** [comment]
Hah, yes, that's wrong. Too much convenience bites back. :slightly_smiling_face: Anyway, maybe pair the `get<Type>Value()` getters with respective `set<Type>Value()` setters, to eliminate ambiguity?

**Comment by mivoligo** [comment]
> Hah, yes, that's wrong. Too much convenience bites back. slightly_smiling_face Anyway, maybe pair the `get<Type>Value()` getters with respective `set<Type>Value()` setters, to eliminate ambiguity?

Looks like quite a big change :slightly_smiling_face:  `setValue` is used more than 130 times :smile: 

BTW shouldn't this line:
https://github.com/Feichtmeier/settings/blob/32b7b128f0b38a5c3d504ee9112e8f360614808e/lib/services/settings_service.dart#L72
be changed to `if (_values[key] == value) {` ?

**Comment by jpnurmi** [comment]
@Feichtmeier This is why tests pay off 😉
