### ISSUE TITLE
Widget for settings row with some extra options

### ISSUE THREAD

**Issue by mivoligo** [Feichtmeier/settings#37]
While I'm slowly progressing with a11y page, I've noticed a lot of inconsistency in the gnome control center app. One of the issue for me is how a _setting row with extra options_ looks like in different parts of the app. 

Here's couple of examples:

![options](https://user-images.githubusercontent.com/1629120/131746946-25b50bc9-c5cc-4dc3-81bf-f1c86dde3703.png)

1. Current boolean status is visible for a setting. You can click the whole row to open extra options for that settings.
2. Current boolean status is visible along with the button. You can click the button to open extra options for that settings
3. There's boolean switch in the row and the button to open extra settings.
4. Just to show that the option button can have different shape. :)

The question is which kind of design are we going with. Personally I like the option 2.

**Comment by mivoligo** [comment]
Yes. These screenshots are from the default Settings app on Ubuntu 20.04.
--EDIT-- 
Sorry. I'm wrong. Option 2 is actually not for a boolean value. Anyway, I'd like to know your opinions.

**Comment by Feichtmeier** [comment]
I also like the second option except that there should not be "off" displayed but the disabled switch from 3

**Comment by mivoligo** [comment]
OK. There's one case though, when displaying "on" or "off" instead of the switch makes more sense. It is when in the setting options there is more than one way to switch that setting on. The example I've seen in a11y is for Click Assist. It displays "on" when either "simulated secondary click" or "hover click" is enabled. 

![Selection_005](https://user-images.githubusercontent.com/1629120/131819847-bf209ade-dcdc-4967-8b32-444806a24fb4.png)

**Comment by mivoligo** [comment]
This is a screenshot how I did in the a11y branch.

![settings_002](https://user-images.githubusercontent.com/1629120/131908714-e3c2b66c-fd11-433b-8c0f-b333b4be5e30.png)

**Comment by Jupi007** [comment]
Super nice!

**Comment by Feichtmeier** [comment]
Looks very nice indeed! @mivoligo feel free to go with whatever you think is right. I am currently only holding you back 🚀

**Comment by mivoligo** [comment]
Thanks guys :heart: 
We can always change it later, I guess.

**Comment by Feichtmeier** [comment]
I think we are happy with what you did here :) Closing as it is "fixed"
