### ISSUE TITLE
Missing page: region & language settings

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#52]
Must-have-features:

- chose a language
- install languages
- chose a keyboard layout

Relevant implementations:

- GCC ![Peek 2021-09-15 13-02](https://user-images.githubusercontent.com/15329494/133422423-98e5a1fb-3f1a-42a2-99b7-897c5fb8eab1.gif)
![FLAMESHOT_2021-09-15_13-09](https://user-images.githubusercontent.com/15329494/133422940-e7d4fae3-aa90-4fe8-818a-24299ebc8052.png)
- Windows 11

Edit: moved timezone issue to its own issue/page
~~I would consolidate this page with the timezone page, because in my mind this is the same sections. Opinions on this one?~~ @madsrh @mivoligo @jpnurmi @jupi007

**Comment by mivoligo** [comment]
Hmm... Personally I would keep the time settings separate from the language settings. Imagine someone travelling. They might only want to adjust the time settings of their machine. So they would look first for something "time" related.

**Comment by Feichtmeier** [comment]
org.freedesktop.locale1

Method: SetLocale (Array of [String] locale, Boolean interactive) ↦ ()
Property: Locale Array of [String]
