### ISSUE TITLE
Missing page: sharing 

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#59]
Must-have-features:

- Allow screen share
- Allow media share from dirs
- Allow SSH share

Relevant implementations:
- GCC ![sharing](https://user-images.githubusercontent.com/15329494/134399485-02ed4760-c253-45a1-970a-cd746dc79b69.gif)

The computer/host re-naming was moved to the Info page

**Comment by Feichtmeier** [comment]
I just realized that @Jupi007 has put the renaming of the computer into the info page 👍 

If you guys agree with me I would close this issue and remove the "sharing page" from the list of wanted pages as I think that it is not needed to control file and media sharing from settings but rather dedicated apps
CC @mivoligo @madsrh @Jupi007 @jpnurmi

**Comment by madsrh** [comment]
That sounds good to me. I've been pondering what to make of the sharing page since you assigned it to me 🙈 I have never used it.

> Is this the correct place to set a computer name? Wouldn't something like "My computer" fit better?

I guess both places would make sense. OFC only if there's a "sharing" page with additional settings in anyway.

**Comment by mivoligo** [comment]
I never used the sharing page as well. For me it could be removed from settings.

**Comment by Feichtmeier** [comment]
> 
> 
> That sounds good to me. I've been pondering what to make of the sharing page since you assigned it to me 🙈 I have never used it.
> 
> > Is this the correct place to set a computer name? Wouldn't something like "My computer" fit better?
> 
> I guess both places would make sense. OFC only if there's a "sharing" page with additional settings anyway.

There is the very popular app remmina pre-installed which is not connected to this setting in ubuntu as far as I know.

**Comment by Feichtmeier** [comment]
Hmmmm re-thinking this a bit since there are actually three features:

- allow file sharing from pictures/music/video dirs
- allow screen sharing
- allow SSH

So maybe this page makes sense in the end - sorry for the german but I needed to record it from my host to show all features:
![sharing](https://user-images.githubusercontent.com/15329494/134399252-5a7b21f3-e92d-4553-b043-4639146684eb.gif)

**Comment by Feichtmeier** [comment]
I remove this page from the TODO, because gnome will remove it to and we all agreed that it doesn't make much sense.
The host renaming is included in the info page
