### ISSUE TITLE
Missing page: power

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#60]
Must-have-features:

- show charge of the laptop battery
- show charge of connected Bluetooth devices
- select CPU power governor
- select keyboard/display brightness
- select to disable the display after never/X minutes
- auto sleep for never/connected/battery mode
- select what to do when you press the power button

To-be-discussed-features:
- I would not put bluetooth and WIFI toggles in here, it is misleading. If you want to reduce power but do not want to lose your connections you don't know what to do. If you are really sure what you do you go to the dedicated bluetooth/wifi sections

Nice-to-have-features:

Relevant implementations:

- GCC ![FLAMESHOT_2021-09-15_14-54](https://user-images.githubusercontent.com/15329494/133437077-57952231-f2a3-4159-b9ce-a910648bb9fa.png)

**Comment by jpnurmi** [comment]
I can start playing with this later.

**Comment by Feichtmeier** [comment]
Thanks @jpnurmi 👍  😺
