### ISSUE TITLE
Improve setting row with slider

### ISSUE THREAD

**Issue by mivoligo** [Feichtmeier/settings#65]
I think we need a way to reset the value set by a slider to the default value and show the current value. 

Here's my idea. Let me know what you guys think.

![Peek 2021-09-15 20-35](https://user-images.githubusercontent.com/1629120/133498385-8d43e046-5048-401d-b78f-f5847913c3c8.gif)

**Comment by Jupi007** [comment]
Good idea :+1: 
Maybe put the reset icon on the far right?

**Comment by Feichtmeier** [comment]
There should be a way to show the value above the slider. This works for the discrete slider I think 🤔 
Could you show how the reset button looks with primary color?

And nice idea!

**Comment by mivoligo** [comment]
> Maybe put the reset icon on the far right?

I've tried few different layouts and got some different issues with them. This one was the least problematic. I can show issues with other layouts.

**Comment by mivoligo** [comment]
> There should be a way to show the value above the slider. This works for the discrete slider I think thinking
IMO the discrete slider looks ugly :wink: and I think there's no easy way to display label above slider without making it discrete.

> Could you show how the reset button looks with primary color?

![Uploading Selection_001.png…]()

**Comment by Jupi007** [comment]
And what about use soft grey?

**Comment by mivoligo** [comment]
Maybe there's more appropriate icon to symbolize reset. I used  `YaruIcons.refresh`

**Comment by mivoligo** [comment]
> And what about use soft grey?
I used Yaru warmGrey here

![Selection_003](https://user-images.githubusercontent.com/1629120/133501717-76214329-2b80-4c33-ae81-5e5631eb2b7c.png)

**Comment by Feichtmeier** [comment]
Another problem I see is that the default value only happens for gsetting stuff. I am not sure everything has actually a default value? Or does it? Maybe it is enough to just load the app with what gsetting gives you. If the slider is not connected to gsetting we could set our own default value 🤔 
Needs a bit more thought I think

**Comment by mivoligo** [comment]
We can make that an optional property and only show when there's a default value. Anyway, I'll try to experiment a bit and maybe create something like the default value mark in GTK sliders.

**Comment by mivoligo** [comment]
OK, Here's how it can look with a mark showing the default value. I'm not sure about the color and size of the mark.
Screenshot:

![Selection_001](https://user-images.githubusercontent.com/1629120/133774768-61742390-e7cb-4b3f-9b08-3dff8f326773.png)

In action:

![Peek 2021-09-17 12-21](https://user-images.githubusercontent.com/1629120/133774547-6b4a9c55-5145-47e5-a526-3634011d0056.gif)

**Comment by Feichtmeier** [comment]
This is a very nice solution. Looks great ant subtle :+1:
