### ISSUE TITLE
New screen: startup apps

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#77]
We could add this into the apps panel

Opinions? @mivoligo @Jupi007 ?

![grafik](https://user-images.githubusercontent.com/15329494/133888045-64b6d812-3e3a-44b2-820c-fe4c3450572e.png)

**Comment by mivoligo** [comment]
I think it's a good idea :+1:

**Comment by Jupi007** [comment]
Yes, add this to the app panel is a must have imo.
I never understood why this isn't present in GCC.

**Comment by Feichtmeier** [comment]
Closing in favour of https://github.com/Feichtmeier/settings/issues/57 (included this idea there)
